### ISSUE TITLE
Write Model Issue

### ISSUE THREAD

**Issue by jeffdumont** [RSGInc/RSGHB#54]
Got this error when writing out an estimated model.

> writeModel(model)
Error in rep(0, nr * (nc + 1)/2) : invalid 'times' argument

**Comment by jeffkeller87** [comment]
Can you send me the model object you were attempting to write?

**Comment by jeffkeller87** [comment]
The vech function was unable to accommodate 1x1 covariance matrices. Now using lower.tri for the conversion.
