### ISSUE TITLE
Error in calculating p and ll0

### ISSUE THREAD

**Issue by jeffkeller87** [RSGInc/RSGHB#68]
When the arguments of likelihood_user are not named fc and b, an error occurs.

Need to unname the arguments passed to likelihood_user on lines 426 and 428 of doHB

**Comment by chasec** [comment]
This seems easy enough - the alternative being that the arguments are unnamed parameters and are matched by position, which means we would need to require the user specify that the *first* two  arguments  in their likelihood correspond to "fc" and "b". We may want to add a check in `checkModel()` to ensure that a minimum of two arguments are listed, via something like this: `length(formals(likelihood))`

**Comment by jeffkeller87** [comment]
I think the documentation/vignette says that there should be arguments “fc” and “b”, so I think it’s okay that we enforce the presence of these two arguments by name. That’s probably easier on users than matching up positional requirements. This came about because Stephane wanted to name “b” and “C” for some reason.

I’m actually leaning towards a no-change decision on this one. What do you think? Perhaps just add all(c(“fc”, “b”) %in% names(formals(likelihood_user))) as a condition to the checkModel function?

**Comment by chasec** [comment]
Yeah that seems reasonable to me. I will add this to checkModel.
