### ISSUE TITLE
checkModel.R check of the likelihood function

### ISSUE THREAD

**Issue by chasec** [RSGInc/RSGHB#70]
Lines 35-39 check whether or not the likelihood function exists. However, likelihood() is defined internally by the doHB() command so I don't see how it would not be defined.

I think this is supposed to reference likelihood_user(), which IS something that the user defines, and if does not exist / is not passed into doHB, will break the likelihood() function itself.

Am I missing something?

**Comment by jeffkeller87** [comment]
This might be extraneous at this point. Will let Jeff D comment.

**Comment by chasec** [comment]
I do think it's extraneous, but we probably do want to check that the likelihood_user function is defined AND it contains parameters "fc"and "b", referencing issue #68 from earlier today.

Will let Jeff D comment and I can make changes from there.

**Comment by jeffkeller87** [comment]
likelihood_user is a non-optional argument to doHB, so if it wasn't supplied by the user, R would throw an error long before the checkModel function is called. However, someone could supply a value for likelihood_user, but maybe they did likelihood_user = "banana". Then, we might want to check that class(likelihood_user) == "function" in checkModel.

**Comment by jeffdumont** [comment]
I think checking that it is a function and has the appropriate parameters
makes sense. Is that the question?

It should be done on likelihood_user and not likelihood.
